identifier: seeeduino_xiao
name: Seeeduino XIAO
type: mcu
arch: arm
ram: 32
flash: 256
toolchain:
  - zephyr
  - gnuarmemb
  - xtools
supported:
  - dma
  - gpio
  - hwinfo
  - pinmux
  - spi
  - i2c
  - uart
  - usb_device
  - watchdog
